import { SERIES } from "@/lib/products";
import type {
  Account,
  Activity,
  CaseRecord,
  Contact,
  DemoUser,
  InventoryLot,
  Invoice,
  OperationsData,
  OrderLine,
  PurchaseOrder,
  Quote,
  QuoteLine,
  QuoteRequest,
  SalesOrder,
  Sku,
  SkuDocument,
  Task,
  Warehouse,
} from "./types";

export const demoAccounts: Account[] = [
  {
    id: "acct-internal",
    type: "internal",
    name: "Summit HVAC Supply",
    status: "active",
    priceTier: "internal",
    creditLimit: 0,
    balance: 0,
    serviceArea: "CA, OR, WA, NV, AZ",
  },
  {
    id: "acct-dealer-bay",
    type: "dealer",
    name: "Bay Area Mechanical Supply",
    status: "active",
    priceTier: "gold",
    creditLimit: 75000,
    balance: 8420,
    serviceArea: "California",
    licenseNumber: "C20-983422",
  },
  {
    id: "acct-installer-summit",
    type: "installer",
    name: "Summit HVAC Installers",
    status: "active",
    priceTier: "standard",
    creditLimit: 25000,
    balance: 1280,
    serviceArea: "California",
    licenseNumber: "C20-771144",
  },
  {
    id: "acct-homeowner-chen",
    type: "homeowner",
    name: "Maria Chen Residence",
    status: "active",
    priceTier: "retail_referral",
    creditLimit: 0,
    balance: 0,
    serviceArea: "San Jose, CA",
  },
  {
    id: "acct-supplier-tcl",
    type: "supplier",
    name: "TCL HVAC North America",
    status: "active",
    priceTier: "supplier",
    creditLimit: 0,
    balance: 0,
  },
];

export const demoContacts: Contact[] = [
  {
    id: "contact-andre",
    accountId: "acct-dealer-bay",
    name: "Andre Lewis",
    email: "andre@bayareamech.example",
    phone: "(415) 555-0144",
    role: "Purchasing Manager",
  },
  {
    id: "contact-nina",
    accountId: "acct-installer-summit",
    name: "Nina Patel",
    email: "nina@summithvac.example",
    phone: "(510) 555-0198",
    role: "Owner",
  },
  {
    id: "contact-maria",
    accountId: "acct-homeowner-chen",
    name: "Maria Chen",
    email: "maria.chen@example.com",
    phone: "(408) 555-0188",
    role: "Homeowner",
  },
];

export const demoUsers: DemoUser[] = [
  {
    id: "user-staff",
    accountId: "acct-internal",
    role: "staff",
    name: "Operations Manager",
    email: "ops@summithvacsupply.example",
  },
  {
    id: "user-dealer",
    accountId: "acct-dealer-bay",
    role: "dealer",
    name: "Andre Lewis",
    email: "andre@bayareamech.example",
  },
  {
    id: "user-installer",
    accountId: "acct-installer-summit",
    role: "installer",
    name: "Nina Patel",
    email: "nina@summithvac.example",
  },
  {
    id: "user-homeowner",
    accountId: "acct-homeowner-chen",
    role: "homeowner",
    name: "Maria Chen",
    email: "maria.chen@example.com",
  },
];

export const demoSkus: Sku[] = [
  {
    id: "sku-brz-09",
    seriesSlug: "breezein",
    sku: "TH09SVH23BW",
    modelNumber: "TH09SVH23BW",
    title: "BreezeIN 9K Wall Mount Heat Pump",
    btu: 9000,
    voltage: "115V",
    unitType: "single-zone wall mount",
    cost: 515,
    dealerPrice: 670,
    msrp: 859,
    dimensions: "31.5 x 8.3 x 11.6 in",
    weightLbs: 20,
    refrigerant: "R-32",
    ahriReference: "AHRI 209748120",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-brz-12",
    seriesSlug: "breezein",
    sku: "TH12SVH23BWE",
    modelNumber: "TH12SVH23BWE",
    title: "BreezeIN 12K Wall Mount Heat Pump",
    btu: 12000,
    voltage: "208/230V",
    unitType: "single-zone wall mount",
    cost: 600,
    dealerPrice: 780,
    msrp: 999,
    dimensions: "31.5 x 8.3 x 11.6 in",
    weightLbs: 22,
    refrigerant: "R-32",
    ahriReference: "AHRI 209748121",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-brz-18",
    seriesSlug: "breezein",
    sku: "TH18SVH22XWE",
    modelNumber: "TH18SVH22XWE",
    title: "BreezeIN 18K Wall Mount Heat Pump",
    btu: 18000,
    voltage: "208/230V",
    unitType: "single-zone wall mount",
    cost: 720,
    dealerPrice: 935,
    msrp: 1199,
    dimensions: "41.3 x 8.9 x 12.8 in",
    weightLbs: 31,
    refrigerant: "R-32",
    ahriReference: "AHRI 209748122",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-brz-24",
    seriesSlug: "breezein",
    sku: "TH24SVH22XWE",
    modelNumber: "TH24SVH22XWE",
    title: "BreezeIN 24K Wall Mount Heat Pump",
    btu: 24000,
    voltage: "208/230V",
    unitType: "single-zone wall mount",
    cost: 810,
    dealerPrice: 1055,
    msrp: 1349,
    dimensions: "41.3 x 8.9 x 12.8 in",
    weightLbs: 34,
    refrigerant: "R-32",
    ahriReference: "AHRI 209748123",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-elt-09",
    seriesSlug: "elite",
    sku: "TSC-09HA2/I3TI23",
    modelNumber: "TSC-09HA2/I3TI23",
    title: "Elite 9K Hyper-Heat Pump",
    btu: 9000,
    voltage: "115V",
    unitType: "single-zone wall mount",
    cost: 630,
    dealerPrice: 820,
    msrp: 1049,
    dimensions: "32.5 x 8.7 x 12.2 in",
    weightLbs: 22,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210114090",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek","NEEP Listed"],
  },
  {
    id: "sku-elt-12",
    seriesSlug: "elite",
    sku: "TSC-12HA2/I3TI23",
    modelNumber: "TSC-12HA2/I3TI23",
    title: "Elite 12K Hyper-Heat Pump",
    btu: 12000,
    voltage: "208/230V",
    unitType: "single-zone wall mount",
    cost: 690,
    dealerPrice: 895,
    msrp: 1149,
    dimensions: "32.5 x 8.7 x 12.2 in",
    weightLbs: 24,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210114091",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR Most Efficient","ETL Intertek","NEEP Listed"],
  },
  {
    id: "sku-elt-18",
    seriesSlug: "elite",
    sku: "TSC-18HA2/I3TI23",
    modelNumber: "TSC-18HA2/I3TI23",
    title: "Elite 18K Hyper-Heat Pump",
    btu: 18000,
    voltage: "208/230V",
    unitType: "single-zone wall mount",
    cost: 870,
    dealerPrice: 1130,
    msrp: 1449,
    dimensions: "41.7 x 9.1 x 13.0 in",
    weightLbs: 33,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210114092",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek","NEEP Listed"],
  },
  {
    id: "sku-elt-24",
    seriesSlug: "elite",
    sku: "TSC-24HA2/I3TI20",
    modelNumber: "TSC-24HA2/I3TI20",
    title: "Elite 24K Hyper-Heat Pump",
    btu: 24000,
    voltage: "208/230V",
    unitType: "single-zone wall mount",
    cost: 990,
    dealerPrice: 1285,
    msrp: 1649,
    dimensions: "41.7 x 9.1 x 13.0 in",
    weightLbs: 37,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210114093",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek","NEEP Listed"],
  },
  {
    id: "sku-frs-12",
    seriesSlug: "freshin",
    sku: "TCL-FRESHIN-12",
    modelNumber: "FreshIN 12K FAS",
    title: "FreshIN 12K Fresh-Air Split",
    btu: 12000,
    voltage: "208/230V",
    unitType: "fresh-air wall mount",
    cost: 990,
    dealerPrice: 1285,
    msrp: 1649,
    dimensions: "39.4 x 8.5 x 12.6 in",
    weightLbs: 29,
    refrigerant: "R-32",
    ahriReference: "AHRI 209990120",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-frs-18",
    seriesSlug: "freshin",
    sku: "TCL-FRESHIN-18",
    modelNumber: "FreshIN 18K FAS",
    title: "FreshIN 18K Fresh-Air Split",
    btu: 18000,
    voltage: "208/230V",
    unitType: "fresh-air wall mount",
    cost: 1140,
    dealerPrice: 1480,
    msrp: 1899,
    dimensions: "43.3 x 8.9 x 13.0 in",
    weightLbs: 34,
    refrigerant: "R-32",
    ahriReference: "AHRI 209990121",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-mz-18",
    seriesSlug: "multi-zone",
    sku: "TUM-18HA2/I2I22",
    modelNumber: "TUM-18HA2/O + 2x TWH-09",
    title: "Multi-Zone 18K 2-Zone System",
    btu: 18000,
    voltage: "208/230V",
    unitType: "multi-zone system",
    cost: 1320,
    dealerPrice: 1715,
    msrp: 2199,
    dimensions: "31.9 x 13.0 x 21.7 in",
    weightLbs: 99,
    refrigerant: "R-410A",
    ahriReference: "AHRI 210201180",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-mz-36",
    seriesSlug: "multi-zone",
    sku: "TUM-36HA2/I2I22-21ES",
    modelNumber: "TUM-36HA2/I2I22-21ES",
    title: "Multi-Zone 36K 2-4 Zone Condenser",
    btu: 36000,
    voltage: "208/230V",
    unitType: "multi-zone outdoor",
    cost: 1500,
    dealerPrice: 1950,
    msrp: 2499,
    dimensions: "37.4 x 15.7 x 31.5 in",
    weightLbs: 143,
    refrigerant: "R-410A",
    ahriReference: "AHRI 210201360",
    warrantyCompressor: "7-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-lc-36",
    seriesSlug: "light-commercial",
    sku: "TSC-36HAI/I3TX22",
    modelNumber: "TSC-36HAI/I3TX22",
    title: "Light Commercial 36K Ceiling Cassette",
    btu: 36000,
    voltage: "208/230V",
    unitType: "ceiling cassette",
    cost: 1740,
    dealerPrice: 2260,
    msrp: 2899,
    dimensions: "33.5 x 33.5 x 11.0 in",
    weightLbs: 70,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210330360",
    warrantyCompressor: "10-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-lc-48",
    seriesSlug: "light-commercial",
    sku: "TSC-48HAI/I3TX22",
    modelNumber: "TSC-48HAI/I3TX22",
    title: "Light Commercial 48K Ceiling Cassette",
    btu: 48000,
    voltage: "208/230V",
    unitType: "ceiling cassette",
    cost: 2100,
    dealerPrice: 2730,
    msrp: 3499,
    dimensions: "33.5 x 33.5 x 12.6 in",
    weightLbs: 84,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210330480",
    warrantyCompressor: "10-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ETL Intertek"],
  },
  {
    id: "sku-cd-36",
    seriesSlug: "central-system",
    sku: "TCA-36CHP/I3TX",
    modelNumber: "TCA-36CHP + air handler",
    title: "Central Ducted 36K (3-Ton) System",
    btu: 36000,
    voltage: "208/230V",
    unitType: "central ducted",
    cost: 1980,
    dealerPrice: 2575,
    msrp: 3299,
    dimensions: "35.4 x 35.4 x 28.7 in",
    weightLbs: 165,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210440360",
    warrantyCompressor: "10-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
  {
    id: "sku-cd-48",
    seriesSlug: "central-system",
    sku: "TCA-48CHP/I3TX",
    modelNumber: "TCA-48CHP + air handler",
    title: "Central Ducted 48K (4-Ton) System",
    btu: 48000,
    voltage: "208/230V",
    unitType: "central ducted",
    cost: 2400,
    dealerPrice: 3120,
    msrp: 3999,
    dimensions: "37.4 x 37.4 x 30.7 in",
    weightLbs: 190,
    refrigerant: "R-454B",
    ahriReference: "AHRI 210440480",
    warrantyCompressor: "10-year",
    warrantyParts: "5-year",
    certifications: ["AHRI Certified","ENERGY STAR","ETL Intertek"],
  },
];

export const demoSkuDocuments: SkuDocument[] = demoSkus.flatMap((sku) => [
  {
    id: `${sku.id}-spec`,
    skuId: sku.id,
    kind: "spec_sheet",
    title: `${sku.title} Spec Sheet`,
    storagePath: `mock-documents/spec-sheets/${sku.sku}.pdf`,
  },
  {
    id: `${sku.id}-manual`,
    skuId: sku.id,
    kind: "install_manual",
    title: `${sku.title} Install Manual`,
    storagePath: `mock-documents/install-manuals/${sku.sku}.pdf`,
  },
]);

export const demoWarehouses: Warehouse[] = [
  {
    id: "wh-nwk",
    code: "NWK",
    name: "Newark Fulfillment Center",
    address: "5437 Central Ave., Suite 10, Newark, CA 94560",
  },
];

export const demoInventoryLots: InventoryLot[] = [
  { id: "lot-brz-09", skuId: "sku-brz-09", warehouseId: "wh-nwk", binCode: "A-01", lotCode: "NWK-BRZ09-0426", onHand: 48, reserved: 6, reorderPoint: 8 },
  { id: "lot-brz-12", skuId: "sku-brz-12", warehouseId: "wh-nwk", binCode: "A-01", lotCode: "NWK-BRZ12-0426", onHand: 36, reserved: 5, reorderPoint: 8 },
  { id: "lot-brz-18", skuId: "sku-brz-18", warehouseId: "wh-nwk", binCode: "A-02", lotCode: "NWK-BRZ18-0426", onHand: 27, reserved: 4, reorderPoint: 6 },
  { id: "lot-brz-24", skuId: "sku-brz-24", warehouseId: "wh-nwk", binCode: "A-02", lotCode: "NWK-BRZ24-0426", onHand: 18, reserved: 4, reorderPoint: 6 },
  { id: "lot-elt-09", skuId: "sku-elt-09", warehouseId: "wh-nwk", binCode: "B-04", lotCode: "NWK-ELT09-0426", onHand: 24, reserved: 2, reorderPoint: 8 },
  { id: "lot-elt-12", skuId: "sku-elt-12", warehouseId: "wh-nwk", binCode: "B-04", lotCode: "NWK-ELT12-0426", onHand: 31, reserved: 6, reorderPoint: 8 },
  { id: "lot-elt-18", skuId: "sku-elt-18", warehouseId: "wh-nwk", binCode: "B-05", lotCode: "NWK-ELT18-0426", onHand: 14, reserved: 3, reorderPoint: 6 },
  { id: "lot-elt-24", skuId: "sku-elt-24", warehouseId: "wh-nwk", binCode: "B-05", lotCode: "NWK-ELT24-0426", onHand: 7, reserved: 7, reorderPoint: 6 },
  { id: "lot-frs-12", skuId: "sku-frs-12", warehouseId: "wh-nwk", binCode: "A-03", lotCode: "NWK-FRS12-0426", onHand: 5, reserved: 3, reorderPoint: 6 },
  { id: "lot-frs-18", skuId: "sku-frs-18", warehouseId: "wh-nwk", binCode: "A-03", lotCode: "NWK-FRS18-0426", onHand: 4, reserved: 1, reorderPoint: 4 },
  { id: "lot-mz-18", skuId: "sku-mz-18", warehouseId: "wh-nwk", binCode: "C-05", lotCode: "NWK-MZ18-0426", onHand: 9, reserved: 2, reorderPoint: 5 },
  { id: "lot-mz-36", skuId: "sku-mz-36", warehouseId: "wh-nwk", binCode: "C-05", lotCode: "NWK-MZ36-0426", onHand: 11, reserved: 5, reorderPoint: 5 },
  { id: "lot-lc-36", skuId: "sku-lc-36", warehouseId: "wh-nwk", binCode: "C-02", lotCode: "NWK-LC36-0426", onHand: 3, reserved: 1, reorderPoint: 4 },
  { id: "lot-lc-48", skuId: "sku-lc-48", warehouseId: "wh-nwk", binCode: "C-02", lotCode: "NWK-LC48-0426", onHand: 2, reserved: 1, reorderPoint: 3 },
  { id: "lot-cd-36", skuId: "sku-cd-36", warehouseId: "wh-nwk", binCode: "D-01", lotCode: "NWK-CD36-0426", onHand: 4, reserved: 2, reorderPoint: 3 },
  { id: "lot-cd-48", skuId: "sku-cd-48", warehouseId: "wh-nwk", binCode: "D-01", lotCode: "NWK-CD48-0426", onHand: 2, reserved: 2, reorderPoint: 3 },
];

export const demoQuoteRequests: QuoteRequest[] = [
  {
    id: "qr-1048",
    name: "Andre Lewis",
    email: "andre@bayareamech.example",
    phone: "(415) 555-0144",
    need: "Three Elite 9k systems for San Mateo tenant improvement.",
    status: "new",
    createdAt: "2026-06-05T16:20:00.000Z",
    lines: [{
      skuId: "sku-elt-09",
      sku: "TCL-ELT-09HP-230",
      modelNumber: "ELITE-09-230V",
      productName: "Elite 9k Premium Heat Pump",
      quantity: 3,
    }],
  },
];

export const demoQuotes: Quote[] = [
  {
    id: "quote-1042",
    quoteNumber: "Q-2026-1042",
    accountId: "acct-dealer-bay",
    status: "sent",
    subtotal: 3270,
    tax: 294.3,
    total: 3564.3,
    validUntil: "2026-06-20",
  },
];

export const demoQuoteLines: QuoteLine[] = [
  { quoteId: "quote-1042", skuId: "sku-elt-09", quantity: 3, unitPrice: 1090, lineTotal: 3270 },
];

export const demoSalesOrders: SalesOrder[] = [
  {
    id: "so-2217",
    orderNumber: "SO-2026-2217",
    quoteId: "quote-1042",
    accountId: "acct-dealer-bay",
    status: "reserved",
    subtotal: 3270,
    total: 3564.3,
  },
];

export const demoOrderLines: OrderLine[] = [
  {
    orderId: "so-2217",
    skuId: "sku-elt-09",
    quantity: 3,
    reservedQuantity: 3,
    shippedQuantity: 0,
    unitPrice: 1090,
  },
];

export const demoInvoices: Invoice[] = [
  {
    id: "inv-1884",
    invoiceNumber: "INV-2026-1884",
    orderId: "so-2217",
    accountId: "acct-dealer-bay",
    status: "open",
    subtotal: 3270,
    tax: 294.3,
    total: 3564.3,
    paid: 0,
    balance: 3564.3,
    dueDate: "2026-07-06",
  },
  {
    id: "inv-1769",
    invoiceNumber: "INV-2026-1769",
    accountId: "acct-dealer-bay",
    status: "overdue",
    subtotal: 4855,
    tax: 436.95,
    total: 5291.95,
    paid: 436.25,
    balance: 4855.7,
    dueDate: "2026-05-29",
  },
];

export const demoPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po-3311",
    poNumber: "PO-2026-3311",
    supplierAccountId: "acct-supplier-tcl",
    status: "sent",
    total: 19580,
    expectedAt: "2026-06-15",
  },
];

export const demoRmas: CaseRecord[] = [
  {
    id: "rma-019",
    number: "RMA-2026-019",
    accountId: "acct-dealer-bay",
    skuId: "sku-elt-09",
    status: "waiting",
    title: "Cabinet dent on received indoor unit",
    detail: "Waiting on dealer photos before replacement approval.",
  },
];

export const demoWarrantyClaims: CaseRecord[] = [
  {
    id: "wr-044",
    number: "WR-2026-044",
    accountId: "acct-installer-summit",
    skuId: "sku-brz-09",
    status: "open",
    title: "Intermittent fan motor fault",
    detail: "Needs serial photo and startup checklist.",
  },
];

export const demoRebateCases: CaseRecord[] = [
  {
    id: "reb-082",
    number: "REB-2026-082",
    accountId: "acct-installer-summit",
    status: "open",
    title: "TECH Clean California packet",
    detail: "Maria Chen project needs AHRI certificate, invoice, and install photos.",
  },
];

export const demoTasks: Task[] = [
  {
    id: "task-quote-expiry",
    accountId: "acct-dealer-bay",
    title: "Follow up on Q-2026-1042 before quote expires",
    ownerRole: "staff",
    status: "open",
    dueAt: "2026-06-08T16:00:00.000Z",
  },
  {
    id: "task-warranty-photo",
    accountId: "acct-installer-summit",
    title: "Collect serial number photo for warranty claim WR-2026-044",
    ownerRole: "installer",
    status: "open",
    dueAt: "2026-06-07T18:00:00.000Z",
  },
  {
    id: "task-homeowner-referral",
    accountId: "acct-homeowner-chen",
    title: "Match homeowner with South Bay installer",
    ownerRole: "staff",
    status: "open",
    dueAt: "2026-06-06T20:00:00.000Z",
  },
];

export const demoActivity: Activity[] = [
  {
    id: "act-quote-sent",
    accountId: "acct-dealer-bay",
    event: "Quote sent to dealer",
    entityType: "quote",
    entityId: "quote-1042",
    createdAt: "2026-06-05T18:10:00.000Z",
  },
  {
    id: "act-invoice-opened",
    accountId: "acct-dealer-bay",
    event: "Invoice opened with AR balance",
    entityType: "invoice",
    entityId: "inv-1884",
    createdAt: "2026-06-05T18:30:00.000Z",
  },
  {
    id: "act-referral",
    accountId: "acct-homeowner-chen",
    event: "Homeowner referral case created",
    entityType: "task",
    createdAt: "2026-06-06T04:15:00.000Z",
  },
];

export function createDemoOperationsData(): OperationsData {
  return {
    accounts: demoAccounts,
    contacts: demoContacts,
    users: demoUsers,
    skus: demoSkus,
    skuDocuments: demoSkuDocuments,
    warehouses: demoWarehouses,
    inventoryLots: demoInventoryLots,
    quoteRequests: demoQuoteRequests,
    quotes: demoQuotes,
    quoteLines: demoQuoteLines,
    salesOrders: demoSalesOrders,
    orderLines: demoOrderLines,
    invoices: demoInvoices,
    purchaseOrders: demoPurchaseOrders,
    rmas: demoRmas,
    warrantyClaims: demoWarrantyClaims,
    rebateCases: demoRebateCases,
    tasks: demoTasks,
    activity: demoActivity,
  };
}

export function getSeriesName(slug: string): string {
  return SERIES.find((series) => series.slug === slug)?.name ?? slug;
}
